# Change these first
owner: lzh-zone # Your GitHub organization or username, where this repository lives
repo: lin-uptime # The name of this repository

sites:
  - name: 监控页
    url: https://lzhnb.cf
  - name: blog
    url: https://blog.lzhnb.cf
  - name: blogn
    url: https://new.lzhnb.cf
  - name: 影视1
    url: https://z.lzh1.eu.org
  - name: 影视2
    url: https://fei.lzhpri.tk
  - name: yu1
    url: https://xiaoyuer.tv/api.php/timming/index.html?enforce=1&name=aa
  - name: yu2
    url: https://xiaoyuer.tv/api.php/timming/index.html?enforce=1&name=bb
  - name: free.nl.eu.org-ff
    url: https://free.nl.eu.org/api.php/timming/index.html?enforce=1&name=093a8fb6e9ff09dabd984a30349bd5e2collect01
  - name: free.nl.eu.org-hy
    url: https://free.nl.eu.org/api.php/timming/index.html?enforce=1&name=8b1572c70defb898e69519f7abc2d36bcollect04
  - name: free.nl.eu.org-lz
    url: https://free.nl.eu.org/api.php/timming/index.html?enforce=1&name=cc427cd482f68237e1b77e5f11a1e28acollect09
  - name: free.nl.eu.org-hn
    url: https://free.nl.eu.org/api.php/timming/index.html?enforce=1&name=5ea090f24f65a22bd9b9c8737ee53872collect12
  - name: free.nl.eu.org-hh
    url: https://free.nl.eu.org/api.php/timming/index.html?enforce=1&name=huohuzyzanzhu09
  - name: free.nl.eu.org-js
    url: https://free.nl.eu.org/api.php/timming/index.html?enforce=1&name=jisuzyzanzhu14
  - name: free.nl.eu.org-sl
    url: https://free.nl.eu.org/api.php/timming/index.html?enforce=1&name=senlinzyzanzhu12
    
    
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: mo.mrlin.me
  # baseUrl: /your-repo-name
  logoUrl: https://cdn.jsdelivr.net/gh/lzh-zone/pic@main/img/logo.png
  name: 小林监控
  introTitle: "小林的网站监控"
  introMessage: <script type="text/javascript" src="https://v1.hitokoto.cn/?format=js&charset=utf-8"></script> <div id="hitokoto"><script>hitokoto ()</script></div>
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
