# Change these first
owner: lzh-zone # Your GitHub organization or username, where this repository lives
repo: lin-uptime # The name of this repository

sites:
  - name: pan-serv00
    url: https://pan.wzz.cloudns.ch
    maxResponseTime: 4000
  - name: blog
    url: https://010702.xyz
  - name: memo
    url: https://memo.010702.xyz
  - name: 0702影院
    url: https://0702.rr.nu/
    maxResponseTime: 8000
  - name: 毒蛇影院
    url: https://ds.872888.xyz/
    maxResponseTime: 8000
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: FC影院
    url: https://v.872888.xyz/
    maxResponseTime: 8000
    expectedStatusCodes:
      - 200
      - 201
      - 403
    
    
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: mo.wzz.cloudns.ch
  # baseUrl: /your-repo-name
  logoUrl: https://cdn.jsdelivr.net/gh/lzh-zone/pic@main/img/logo.png
  name: 小林监控
  introTitle: "小林的网站监控"
  introMessage: <script type="text/javascript" src="https://v1.hitokoto.cn/?format=js&charset=utf-8"></script> <div id="hitokoto"><script>hitokoto ()</script></div>
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration


