# Change these first
owner: lzh-zone # Your GitHub organization or username, where this repository lives
repo: lin-uptime # The name of this repository

sites:
  - name: 监控页
    url: https://lzhnb.cf
  - name: blog
    url: https://blog.lzhnb.cf
  - name: blogn
    url: https://new.lzhnb.cf
  - name: 影视
    url: https://be.lzhpri.tk/api.php/timming/index.html?enforce=1&name=hongniu

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: mo.mrlin.me
  # baseUrl: /your-repo-name
  logoUrl: https://cdn.jsdelivr.net/gh/lzh-zone/pic@main/img/logo.png
  name: 小林监控
  introTitle: "小林的网站监控"
  introMessage: <script type="text/javascript" src="https://v1.hitokoto.cn/api/?format=js&charset=utf-8"></script> <div id="hitokoto"><script>hitokoto ()</script></div>
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
