# Change these first
owner: lzh-zone # Your GitHub organization or username, where this repository lives
repo: lin-uptime # The name of this repository

sites:
  - name: pan-serv00
    url: https://xxx.wzz.cloudns.ch
  - name: blog
    url: https://blog.lzhnb.cf
  - name: blogn
    url: https://new.lzhnb.cf
  - name: 影视1
    url: https://z.lzh1.eu.org
  - name: 影视2
    url: https://fei.lzhpri.tk
  - name: free.nl.eu.org
    url: https://free.nl.eu.org/

    
    
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: mo.wzz.cloudns.ch
  # baseUrl: /your-repo-name
  logoUrl: https://cdn.jsdelivr.net/gh/lzh-zone/pic@main/img/logo.png
  name: 小林监控
  introTitle: "小林的网站监控"
  introMessage: <script type="text/javascript" src="https://v1.hitokoto.cn/?format=js&charset=utf-8"></script> <div id="hitokoto"><script>hitokoto ()</script></div>
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
